### ISSUE TITLE
Doesn't seem to work if node being updated is the first in the program

### ISSUE THREAD

**Issue by ntdaley** [sindresorhus/rocambole-node-update#1]
When the node being replaced is not the first in the program, it gets updated correctly.

```
> rocambole.moonwalk('a=0;$log.log()', function(node) { if( node.type === 'CallExpression' && node.callee.object.name ==='$log' ) { updateNode(node, 'void 0'); } }).toString()
'a=0;void 0'
> 
```

When a node being updated is the first in the program, it does not get updated.

```
> rocambole.moonwalk('$log.log()', function(node) { if( node.type === 'CallExpression' && node.callee.object.name ==='$log' ) { updateNode(node, 'void 0'); } }).toString()
'$log.log()'
```

It looks like prev and next references for sibling nodes get updated, but whatever references the parent node has do not get updated.

**Comment by sindresorhus** [comment]
Weird, but I just modulified what's in the Rocambole readme: https://github.com/millermedeiros/rocambole#linked-list

Maybe @millermedeiros would know?
